name: Deploy to Public GitHub Pages

on:
  push:
    branches:
      - main  # Ganti ke 'master' kalau branch utama kamu bukan 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode dari repo private
        uses: actions/checkout@v3

      # Langkah build (opsional, kalau kamu pakai tools seperti Vite, React, dll)
      # - name: Build proyek
      #   run: npm install && npm run build

      - name: Deploy ke repo publik (GitHub Pages)
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.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 }}
          external_repository: Admin-Dekstop/Tanya_Dataa  # Ganti sesuai nama repo publik kamu
          publish_branch: gh-pages  # Branch khusus GitHub Pages
          publish_dir: ./dist       # Ganti ke folder tempat file HTML kamu berada
          force_orphan: true
          commit_message: "🚀 Deploy otomatis dari repo private"
