name: Deploy Static HTML to GitHub Pages

on:
  push:
    branches:
      - main  # Ganti kalau branch utama lu bukan 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages (public repo)
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.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 }}
          external_repository: Admin-Dekstop/Hosting-TanyaData
          publish_branch: gh-pages
          publish_dir: ./dist
          force_orphan: true
          commit_message: "🚀 Auto deploy from private repo"
